\chapter{Previous literature in L3 phonology}

# Previous literature in L3 phonology

In the research to date, L3 models have focused largely on empirical results stemming from experiments in morpho-syntax to derive predictions about how the L1 and L2 affect L3 acquisition. 
Fewer studies have been conducted in L3 phonology, and it remains unclear whether L3 models make specific predictions for phonology and morphosyntax.
Despite this lack of specificity in the models when it comes to phonology, some trends have emerged in the body of research.
Specifically, it appears that the L1 and L2 likely both affect L3 perception and production, with the L2 often providing a greater level of influence in the beginning stages of acquisition, even when it is not facilitative. 
This trend cannot readily be accounted for by the TPM, the L2SF, the CEM nor the Scalpel Model, leaving only the LPM which can predicts co-activation of all languages known by a bilingual in L3 acquisition. 
The following sections cover the empirical studies that have been done in L3 production studies across L3 proficiency levels, and the fewer studies done in L3 perception, as well as their relevance to L3 models.  

## L3 Production Studies 

The findings in empirical studies of L3 phonological cross-linguistic influence have varied. 
One of the first studies to examine progressive influence of the L1 or L2 on L3 production was the seminal case study of **Williams and Hammarberg (1993)**. 
This study elicited the production of an adult L1 British English, L2 German, and L3 Swedish speaker in the L2 and L3 upon her arrival to Sweden. 
The speech samples were rated for native-likeness by native speakers of German and Swedish respectively, with low ratings (i.e. non-nativeness) being elaborated upon.
In the event of non-native speech, the raters guessed where the speaker in the recording might be from. 
The informant was rated as having near native productions in her L2 German, while her L3 Swedish was rated as being non-native like and to be German-accented. 
The experiment was repeated after 6 months in Sweden, however, and the Swedish raters then judged the informant's Swedish to be British English accented. 

This study constituted evidence of an L2 status effect in the initial stages of L3 phonological acquisition, in which the second learned language influence L3 production, but also provided evidence that this effect diminishes as L3 proficiency increases.
This notion has been called the ‘foreign language effect’ [@meisel_transfer_1983], which refers to the idea that speakers who learn a second non-native language are biased to sound unlike a native speaker of their native language. 

The default L2 status effect has received some empirical support in the L3 phonology literature.
In a study of global accent production, heavier L2 influence in L3 productions was found by L1 Polish, L2 German and L3 English speakers based on ratings of EFL instructors [@wrembel_l2-accented_2010]. 
Similar findings have also been reported in vowel production *[@kamiyama_acquisition_2007]* vowel reduction and speech rhythm [@gut_cross-linguistic_2010].
L2 influence has also been found in VOT productions.
@llama_influence_2010 examined L3 Spanish VOT production by French-English mirror-image bilingual groups and found that both groups had L2-like productions of the L3. 

Other findings in L3 production, however, have yielded mixed results. 
Several studies have found that acoustic properties of the participants' productions fall between L1 and L3 values, suggesting that both the L1 and the L2 have some influence on L3 productions, rather than solely one language. 
For instance, [@wrembel_vot_2014] measured VOT and aspiration in all languages of participants with two different language combinations: L1 Polish, L2 English, and L3 French; (2) L1 Polish, L2 English, and L3 German. 
The results showed that each language had a specific stop-value, and that the L3 VOT productions were intermediate, falling between the L1 and L2 values. 
Similarly, [@wrembel_cross-linguistic_2011] examined thirty-two learners of L3 French with L1 Polish and L2 English who were recorded reading lists of words in carrier phrases. 
As in previous studies [@wrembel_vot_2014], combined transfer from the L1 and the L2 in VOT productions was found. 
Findings of combined L1 and L2 influence in VOT productions were also reported by @wunder_phonological_2010 in L3 Spanish speakers, and by @blank_transferencia_2009 in L3 English speakers who spoke L1 Brazilian Portuguese and L2 French. 
Other studies have found an L1 influence on production despite L3 proficiency [@wrembel_foreign_2012], or in advanced L3 learners [@llama_revisiting_2018].
Importantly, these studies report L3 VOT values which fall between L1 and L2 values. 
Following the suspicion that intermediate values might have to do with either sampling issues or proficiency effects, **Parrish (2021)** examined Mexican Spanish-English bilinguals who produced voiceless stop-initial French words in isolation at first exposure to the language. 
The results found that the relative VOT of the L3 fell between their own L1 and L2 values, in line with previous research, and that suggested that intermediate values were less likely to have been seen in previous studies as a result of small samples or proficiency effects. 
However, a subsequent analysis of the data suggested that wide individual variation existed in the data, in which some participants produced L3 French as L1 Spanish like, and other produced intermediate, L2-like values. 
This result suggests that higher samples could reveal group trends and provide better insights into individual variation in crosslinguistic influence, as opposed to assuming that a single group trend exists.                  


## L3 Perception studies 

Overall, studies in L3 perception have been much more scarce relative to studies in production.
These few studies have often used methods found in L2 speech acquisition research, such as studies testing the predictions of the Perceptual Assimilation Model.
For instance, @wrembel_extending_2019 examined the categorization and discrimination of L3 vowels by 10 young trilinguals who spoke L1 German-L2 English-L3 Polish.
To test categorization, a cross-linguistic similarity task was used in which participants heard minimal pairs of sounds and had to rate how similar sounds were on a 1-7 Likert scale. 
The results showed evidence that participants assimilated L3 sounds to both L1 and L2 categories, but preferred the L2. 
In a second experiment, and AX discrimination task was given to participants to evaluate whether retroflex and palato-alveolar silibant discrimination, a feature of Polish, could be accessed in L3 words.
The results revealed that discrimination of the L1 Polish contrast was very good (84% accuracy), suggesting that L3 learners retain access to L1 sound contrasts in L3 words.  
Additionally, this language specific phonetic discrimination was attended to by even L3 beginners. 
@balas_non-native_2018 also used the PAM as a perceptual framework to work in and adapted it to L3 learners. 
The study recruited three groups of Polish L1 speakers, including two L3 groups (L1 Polish-L2 English-L3 Dutch and L1 Polish-L2 English-L3 Dutch). 
The third group spoke only English as an L2. 
All three groups were listened to Dutch vowels and were asked to categorize them given Polish vowel categories. 
Unfortunately, the L3 groups were not given L2 English categories as options during this task, so the results of this study cannot directly provide evidence that L3 learners categorize L3 sounds using both the L1 and L2.
The same study also conducted an AXB discrimination task of 8 Dutch vowels and found that discrimination was at ceiling for all vowels involved.

An additional line of research in L3 perception studies has pondered whether L3 learners have a general perceptual advantage over their L2 learning counterparts. 
In an early study, *Werker (1986)* investigated mono, bi and multilingual participants' discrimination of non-native perceptual contrasts and did not find any evidence that the bi or multilingual group had any perceptual advantage. 
*Patihis, Oh and Mogilner (2015)* examined Korean stops by naive mono and multilingual listeners and found that phoneme discrimination was feature dependent, rather than bilingualism providing a general advantage. 
*Antoniou et al. (2013)* investigated the contrast of Ma'di stops by early English-Greek bilinguals, English monolinguals and Greek monolinguals.
The researchers wanted to know whether language mode affected categorization and discrimination. 
They found that categorization is modulated by language mode, but discrimination of novel sounds was not.
In particular, the Greek monolingual group was most successful in the discrimination of the novel contrast, where the English monolingual group was the least accurate. 
The bilingual group, regardless of language mode, displayed intermediate ability to discriminate the novel sounds.
In a further study, *Antoniou et al. (2015)* taught mono and bilingual participants an artificial language based on either English or Mandarin.
The results revealed that bilingual participants outlearned the monolingual groups overall, but universally more difficult unfamiliar L3 segments do no seem to be learned more easily by bilinguals. 
@wrembel_cross-linguistic_2020 also found that cross-linguistic influence is structure dependent and varies among individuals. 
**Onishi (2016)** reported a bilingual advantage, but, rather than feature dependent, suggested that this advantage was global.
The study involved speakers of Korean who spoke L2 English and L3 Japanese.
The author found a correlation between successful discrimination of L3 contrasts and L2 experience, and argued that this correlation is evidence for a bilingual advantage. 
These findings suggest that crosslinguistic similarity of both a bilingual's languages play a role in the ease of acquiring a novel, L3 sound.
Additionally, research focused on a bilingual advantage in phonetic learning can inform L3 models, since it implies that bilinguals have access to the phonetic categories in both languages that they speak, even at first exposure, whether or not the advantages of bilingualism on phonetic learning are global or feature dependent. 
Few studies have investigated the role of VOT in L3 perception. 
On such study is  *@liu_effects_2019*, which examined the perceptual boundary of a VOT continuum in L1 Mandarin, L2 English and L3 Spanish.
Using a /pi-bi/ continuum, the authors found that the perceptual boundaries of each language were 28ms for Chinese, 24.6ms for English and 23ms for Spanish.
Despite the goal of the study being to examine regressive transfer and to compare the L3 speakers to monolinguals, descriptive evidence of L2 effects can be inferred from the reported means.
Additionally, *Liu & Lin (2021)* examined perception and production of word-initial voiced and voiceless stops in speakers of L1 Mandarin, L2 English and L3 Russian or Japanese.
The authors found that voiced stops were effectively perceived, but not reliably produced, where voiceless stops were both successfully perceived and produced. 

